name = "Steampunk Create"
author = "PotentiallyADuck"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac3139f2776deea64704fb110a11d785efd4a60adab5a22e999a4c29484e3f26"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
