name = "Steampunk Create"
author = "PotentiallyADuck"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8d7f22a9ae099247a3e432a36bf39c7eb398a6a15f15a24ea8e3c34e348e838"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
