name = "Steampunk Create"
author = "PotentiallyADuck"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b118317ebb3dd30530c58459ddfb125afe1ac15dfd0d9a720b09f6c649d163fe"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"

[options]
acceptable-game-versions = "1.18.2"
