name = "Steampunk Create"
author = "PotentiallyADuck"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1bf1b45c950c23e06a671ae0cc1acacfed8ee1d5dd81d580882ecc11f94bc6a"

[versions]
fabric = "0.14.13"
minecraft = "1.18.2"

[options]
acceptable-game-versions = "1.18.2"
